// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Our Passion for Baking"
          descriptions={[
            "At The Daily Crumb, every loaf of bread, every delicate pastry, and every celebration cake is baked with love and the finest ingredients. We are a family-owned bakery, dedicated to bringing joy and delicious moments to our community.",
            "For over a decade, we've perfected our recipes, combining traditional techniques with innovative flavors. From early morning deliveries to bespoke wedding cakes, our commitment to quality and freshness shines through in every bite. Come taste the difference!",
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
