// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";
import ActiveBadge from "@/components/ui/ActiveBadge";

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="slide-up">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card">
            <div className="flex flex-col items-center gap-2">
              <div className="flex items-center gap-2 px-4 py-1.5 rounded-full bg-gradient-to-b from-green-400 to-green-600 text-white shadow-[0_0_15px_rgba(34,197,94,0.5)] border border-green-300 mb-2">
                <span className="relative flex h-2.5 w-2.5">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-white opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-white"></span>
                </span>
                <span className="text-xs font-bold tracking-wider uppercase">Active Now</span>
              </div>
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Visit Us or Order Today"}</p>
              </div>

              <TextAnimation
                text={"Ready to indulge? Stop by our bakery, or place your order online for pick-up or delivery. We can't wait to serve you!"}
                variant="fade"
                gradientText={true}
                tag="h2"
                className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance"
              />

              <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
                <Button text={{"text":"Order Now","href":"mailto:orders@thedailycrumb.com"}.text} href={{"text":"Order Now","href":"mailto:orders@thedailycrumb.com"}.href} variant="primary" />
                <Button text={{"text":"Get Directions","href":"https://maps.google.com/maps?q=The+Daily+Crumb"}.text} href={{"text":"Get Directions","href":"https://maps.google.com/maps?q=The+Daily+Crumb"}.href} variant="secondary" animationDelay={0.1} />
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
