// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visit Us or Order Today"
          text="Ready to indulge? Stop by our bakery, or place your order online for pick-up or delivery. We can't wait to serve you!"
          primaryButton={{
            text: "Order Now",
            href: "mailto:orders@thedailycrumb.com",
          }}
          secondaryButton={{
            text: "Get Directions",
            href: "https://maps.google.com/maps?q=The+Daily+Crumb",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
