// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Got Questions?"
          title="Frequently Asked Questions"
          description="Find quick answers to common inquiries about our products, ordering, and services."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "What are your bakery's operating hours?",
                  answer: "We are open Monday to Saturday from 7 AM to 6 PM, and Sunday from 8 AM to 3 PM. Please check our Google Maps listing for any holiday hours.",
                },
                {
                  question: "Do you offer gluten-free or vegan options?",
                  answer: "Yes, we have a selection of delicious gluten-free and vegan pastries available daily. Please ask our staff for today's special selection as it varies.",
                },
                {
                  question: "Where are your ingredients sourced from?",
                  answer: "We pride ourselves on using locally sourced, premium ingredients whenever possible. Our flour comes from local mills, and seasonal fruits are from nearby farms.",
                },
              ],
            },
            {
              name: "Ordering",
              items: [
                {
                  question: "How can I place an online order?",
                  answer: "You can place online orders directly through our website by navigating to the 'Order Now' section. Select your items, choose pick-up or delivery, and complete the checkout process.",
                },
                {
                  question: "What is the lead time for custom cake orders?",
                  answer: "For custom cakes, we require a minimum of 7 days' notice. For intricate designs or large orders, we recommend booking 2-3 weeks in advance to ensure availability.",
                },
                {
                  question: "Do you offer delivery services?",
                  answer: "Yes, we offer local delivery within a 10-mile radius for online orders over $25. Delivery fees apply based on distance. You can check availability at checkout.",
                },
              ],
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
