// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "home" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HomeSection(): React.JSX.Element {
  return (
    <div id="home" data-section="home">
        <SectionErrorBoundary name="home">
              <HeroBillboard
          title="Your Daily Dose of Artisan Freshness"
          description="Artisan breads, pastries, and custom cakes crafted with premium ingredients. Order online or visit us today."
          primaryButton={{
            text: "Order Now",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Our Menu",
            href: "#products",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/top-view-mix-breads-cookies-with-brown-sugar-cubes_23-2148695485.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
