// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "partners" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PartnersSection(): React.JSX.Element {
  return (
    <div id="partners" data-section="partners">
        <SectionErrorBoundary name="partners">
              <SocialProofMarquee
          tag="Trusted Partners"
          title="Proudly Serving Our Community"
          description="We partner with local businesses and events to bring our delicious baked goods further."
          names={[
            "Cafe Delight",
            "Sweet Escapes Catering",
            "Golden Oven Bistro",
            "Morning Muffin Co.",
            "Flourish Foods Market",
            "Dough & Co. Eatery",
            "Sugar & Spice Event Planners",
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
