// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesGridSplit from '@/components/sections/features/FeaturesGridSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesGridSplit
          tag="Beyond the Counter"
          title="Custom Orders & Catering"
          description="Planning a special event or need a personalized cake? We offer bespoke solutions to make your moments extra sweet."
          topItems={[
            {
              title: "Custom Celebration Cakes",
              description: "From elegant wedding cakes to fun birthday creations, we design custom cakes that are as unique as your celebration.",
              imageSrc: "http://img.b2bpic.net/free-photo/sweet-candy-bar-wedding-celebration-party_482257-31517.jpg",
            },
            {
              title: "Event & Corporate Catering",
              description: "Impress your guests or clients with a delightful selection of our finest pastries, mini desserts, and savory treats.",
              imageSrc: "http://img.b2bpic.net/free-photo/candy-bar-with-mousse-desserts-eclairs-patisserie-violet-table_8353-9830.jpg",
            },
          ]}
          bottomItem={{
            title: "Wholesale Partnerships",
            description: "Looking to offer quality baked goods at your café or restaurant? Partner with The Daily Crumb for fresh, reliable supply.",
            primaryButton: {
              text: "Learn More",
              href: "#contact",
            },
            imageSrc: "http://img.b2bpic.net/free-photo/close-up-people-clinking-glasses_23-2149295545.jpg",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
