// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
          tag="Loved by Many"
          title="What Our Customers Say"
          description="Hear from our happy customers who enjoy the freshness and quality of The Daily Crumb."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Local Resident",
              quote: "The sourdough bread from The Daily Crumb is simply the best in town. It's a staple in our household!",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-woman-holding-cupcake_23-2148263228.jpg",
            },
            {
              name: "Michael C.",
              role: "Event Planner",
              quote: "Their custom cakes are true works of art. The attention to detail and flavor are unmatched for our corporate events.",
              imageSrc: "http://img.b2bpic.net/free-photo/family-routine-concept-mixed-race-male-reads-attentively-news-tablet-computer-sits-kitchen_273609-8912.jpg",
            },
            {
              name: "Emily R.",
              role: "Community Member",
              quote: "I love stopping by for my morning coffee and a croissant. The staff are always so friendly, and everything is so fresh.",
              imageSrc: "http://img.b2bpic.net/free-photo/family-cooks-dough-cookies-kitchen_1157-25225.jpg",
            },
            {
              name: "David K.",
              role: "Restaurant Owner",
              quote: "Partnering with The Daily Crumb for our daily bread supply has been fantastic. Our customers rave about the quality.",
              imageSrc: "http://img.b2bpic.net/free-photo/businessmen-laughing_23-2147704583.jpg",
            },
            {
              name: "Jessica L.",
              role: "Student",
              quote: "The muffins are my go-to study snack. Always delicious and gives me the perfect energy boost!",
              imageSrc: "http://img.b2bpic.net/free-photo/father-s-day-composition-with-delicious-croissant_23-2147632064.jpg",
            },
            {
              name: "Robert B.",
              role: "Retiree",
              quote: "This bakery reminds me of my grandmother's kitchen. The classic recipes are just perfect, pure comfort.",
              imageSrc: "http://img.b2bpic.net/free-photo/excited-elegant-middle-aged-businesswoman-using-laptop-work-clenching-fists-happy-win-tender_343059-3753.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
