// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

type Testimonial = {
  name: string;
  role: string;
  quote: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TestimonialsInline = () => {
  const half = Math.ceil([{"name":"Sarah J.","role":"Local Resident","quote":"The sourdough bread from The Daily Crumb is simply the best in town. It's a staple in our household!","imageSrc":"http://img.b2bpic.net/free-photo/close-up-woman-holding-cupcake_23-2148263228.jpg"},{"name":"Michael C.","role":"Event Planner","quote":"Their custom cakes are true works of art. The attention to detail and flavor are unmatched for our corporate events.","imageSrc":"http://img.b2bpic.net/free-photo/family-routine-concept-mixed-race-male-reads-attentively-news-tablet-computer-sits-kitchen_273609-8912.jpg"},{"name":"Emily R.","role":"Community Member","quote":"I love stopping by for my morning coffee and a croissant. The staff are always so friendly, and everything is so fresh.","imageSrc":"http://img.b2bpic.net/free-photo/family-cooks-dough-cookies-kitchen_1157-25225.jpg"},{"name":"David K.","role":"Restaurant Owner","quote":"Partnering with The Daily Crumb for our daily bread supply has been fantastic. Our customers rave about the quality.","imageSrc":"http://img.b2bpic.net/free-photo/businessmen-laughing_23-2147704583.jpg"},{"name":"Jessica L.","role":"Student","quote":"The muffins are my go-to study snack. Always delicious and gives me the perfect energy boost!","imageSrc":"http://img.b2bpic.net/free-photo/father-s-day-composition-with-delicious-croissant_23-2147632064.jpg"},{"name":"Robert B.","role":"Retiree","quote":"This bakery reminds me of my grandmother's kitchen. The classic recipes are just perfect, pure comfort.","imageSrc":"http://img.b2bpic.net/free-photo/excited-elegant-middle-aged-businesswoman-using-laptop-work-clenching-fists-happy-win-tender_343059-3753.jpg"}].length / 2);
  const topRow = [{"name":"Sarah J.","role":"Local Resident","quote":"The sourdough bread from The Daily Crumb is simply the best in town. It's a staple in our household!","imageSrc":"http://img.b2bpic.net/free-photo/close-up-woman-holding-cupcake_23-2148263228.jpg"},{"name":"Michael C.","role":"Event Planner","quote":"Their custom cakes are true works of art. The attention to detail and flavor are unmatched for our corporate events.","imageSrc":"http://img.b2bpic.net/free-photo/family-routine-concept-mixed-race-male-reads-attentively-news-tablet-computer-sits-kitchen_273609-8912.jpg"},{"name":"Emily R.","role":"Community Member","quote":"I love stopping by for my morning coffee and a croissant. The staff are always so friendly, and everything is so fresh.","imageSrc":"http://img.b2bpic.net/free-photo/family-cooks-dough-cookies-kitchen_1157-25225.jpg"},{"name":"David K.","role":"Restaurant Owner","quote":"Partnering with The Daily Crumb for our daily bread supply has been fantastic. Our customers rave about the quality.","imageSrc":"http://img.b2bpic.net/free-photo/businessmen-laughing_23-2147704583.jpg"},{"name":"Jessica L.","role":"Student","quote":"The muffins are my go-to study snack. Always delicious and gives me the perfect energy boost!","imageSrc":"http://img.b2bpic.net/free-photo/father-s-day-composition-with-delicious-croissant_23-2147632064.jpg"},{"name":"Robert B.","role":"Retiree","quote":"This bakery reminds me of my grandmother's kitchen. The classic recipes are just perfect, pure comfort.","imageSrc":"http://img.b2bpic.net/free-photo/excited-elegant-middle-aged-businesswoman-using-laptop-work-clenching-fists-happy-win-tender_343059-3753.jpg"}].slice(0, half);
  const bottomRow = [{"name":"Sarah J.","role":"Local Resident","quote":"The sourdough bread from The Daily Crumb is simply the best in town. It's a staple in our household!","imageSrc":"http://img.b2bpic.net/free-photo/close-up-woman-holding-cupcake_23-2148263228.jpg"},{"name":"Michael C.","role":"Event Planner","quote":"Their custom cakes are true works of art. The attention to detail and flavor are unmatched for our corporate events.","imageSrc":"http://img.b2bpic.net/free-photo/family-routine-concept-mixed-race-male-reads-attentively-news-tablet-computer-sits-kitchen_273609-8912.jpg"},{"name":"Emily R.","role":"Community Member","quote":"I love stopping by for my morning coffee and a croissant. The staff are always so friendly, and everything is so fresh.","imageSrc":"http://img.b2bpic.net/free-photo/family-cooks-dough-cookies-kitchen_1157-25225.jpg"},{"name":"David K.","role":"Restaurant Owner","quote":"Partnering with The Daily Crumb for our daily bread supply has been fantastic. Our customers rave about the quality.","imageSrc":"http://img.b2bpic.net/free-photo/businessmen-laughing_23-2147704583.jpg"},{"name":"Jessica L.","role":"Student","quote":"The muffins are my go-to study snack. Always delicious and gives me the perfect energy boost!","imageSrc":"http://img.b2bpic.net/free-photo/father-s-day-composition-with-delicious-croissant_23-2147632064.jpg"},{"name":"Robert B.","role":"Retiree","quote":"This bakery reminds me of my grandmother's kitchen. The classic recipes are just perfect, pure comfort.","imageSrc":"http://img.b2bpic.net/free-photo/excited-elegant-middle-aged-businesswoman-using-laptop-work-clenching-fists-happy-win-tender_343059-3753.jpg"}].slice(half);

  return (
    <section aria-label="Testimonials section" className="pt-20 pb-10">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Loved by Many"}</p>
          </div>

          <TextAnimation
            text={"What Our Customers Say"}
            variant="fade-blur"
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Hear from our happy customers who enjoy the freshness and quality of The Daily Crumb."}
            variant="fade-blur"
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="fade-blur" className="flex flex-col w-content-width mx-auto">
          <div className="overflow-hidden mask-fade-x">
            <div className="flex w-max animate-marquee-horizontal mb-5" style={{ animationDuration: "30s" }}>
              {[...topRow, ...topRow, ...topRow, ...topRow].map((testimonial, index) => (
                <div key={`top-${index}`} className="flex flex-col justify-between gap-4 xl:gap-5 2xl:gap-6 shrink-0 w-72 md:w-80 mr-5 p-6 xl:p-7 2xl:p-8 rounded card">
                    <p className="text-lg leading-snug line-clamp-3">{testimonial.quote}</p>

                    <div className="flex items-center gap-3">
                      <ImageOrVideo
                        imageSrc={testimonial.imageSrc}
                        videoSrc={testimonial.videoSrc}
                        className="size-10 md:size-11 2xl:size-12 rounded-full object-cover"
                      />
                      <div className="flex flex-col min-w-0">
                        <span className="text-base text-foreground font-semibold leading-snug truncate">{testimonial.name}</span>
                        <span className="text-base text-foreground/75 leading-snug truncate">{testimonial.role}</span>
                      </div>
                    </div>
                </div>
              ))}
            </div>
          </div>

          <div className="overflow-hidden mask-fade-x">
            <div className="flex w-max animate-marquee-horizontal-reverse mb-10" style={{ animationDuration: "30s" }}>
              {[...bottomRow, ...bottomRow, ...bottomRow, ...bottomRow].map((testimonial, index) => (
                <div key={`bottom-${index}`} className="flex flex-col justify-between gap-4 xl:gap-5 2xl:gap-6 shrink-0 w-72 md:w-80 mr-5 p-6 xl:p-7 2xl:p-8 rounded card">
                    <p className="text-lg leading-snug line-clamp-3">{testimonial.quote}</p>

                    <div className="flex items-center gap-3">
                      <ImageOrVideo
                        imageSrc={testimonial.imageSrc}
                        videoSrc={testimonial.videoSrc}
                        className="size-10 md:size-11 2xl:size-12 rounded-full object-cover"
                      />
                      <div className="flex flex-col min-w-0">
                        <span className="text-base text-foreground font-semibold leading-snug truncate">{testimonial.name}</span>
                        <span className="text-base text-foreground/75 leading-snug truncate">{testimonial.role}</span>
                      </div>
                    </div>
                </div>
              ))}
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function TestimonialsSection() {
  return (
    <div data-webild-section="testimonials" id="testimonials">
      <TestimonialsInline />
    </div>
  );
}
